routes/web.php
Route::get('productstatusactive/{id}','ProductController@productstatusactive');
Route::get('productstatusinactive/{id}','ProductController@productstatusinactive');
Route::post('productdetails','ProductController@productdetails');
Route::get('productimage','ProductController@product_image');
Route::post('multiimage','ProductController@multiimage');
Route::get('activecoupon/{id}','couponController@activecoupon');
Route::get('inactivecoupon/{id}','couponController@inactivecoupon');


// Stock

Route::get('/productstock', 'ProductController@productstock');
Route::post('addproductstock','ProductController@addproductstock');
Route::get('/viewproductstock', 'ProductController@viewproductstock');
Route::get('/deletestock/{id}','ProductController@deletestock');
Route::get('/editstock/{id}','ProductController@editstock');
Route::post('/updateproductstock/{id}','ProductController@updateproductstock');
Route::get('/stockreport','ProductController@stockreport');
Route::post('/getsize','ProductController@getsize');
Route::post('/getcolor','ProductController@getcolor');

Route::get('/deleteadminproduct/{id}','ProductController@deleteadminproduct');


Route::get('/deleteadminproduct/{id}','ProductController@deleteadminproduct');

Route::post('/update-multi-image','ProductController@update_multi_image')->name('admin/update-multi-image');
Route::get('/delete-multi-image/{id}','ProductController@delete_multi_image')->name('admin/delete-multi-image');



// other controller
Route::get('/admin/about_us','OtherController@about_us');
Route::post('/updateabout/{id}','OtherController@updateabout_us');

Route::get('/admin/term&condition','OtherController@term');
Route::post('/updateterm/{id}','OtherController@updateterm');

Route::get('/admin/privacy&policy','OtherController@privacy');
Route::post('/updateprivacy/{id}','OtherController@updateprivacy');

Route::get('/admin/cookie-policy','OtherController@cookie');
Route::post('/updatecookie/{id}','OtherController@updatecookie');

Route::get('/admin/purchasing-policy','OtherController@purchasing');
Route::post('/updatepurchasing/{id}','OtherController@updatepurchasing');

Route::get('/admin/return-policy','OtherController@return_policy');
Route::post('/updatereturn/{id}','OtherController@updatereturn');

Route::get('/admin/seller-policy','OtherController@seller_policy');
Route::post('/updateseller/{id}','OtherController@updateseller');

Route::get('/admin/merchant-zone','OtherController@merchant_zone');
Route::post('/updatemerchantzone/{id}','OtherController@updatemerchantzone');

Route::get('/admin/seller-zone','OtherController@seller_zone');
Route::post('/updatesellerzone/{id}','OtherController@updatesellerzone');

Route::get('/admin/faq','OtherController@faq');
Route::post('/updatefaq/{id}','OtherController@updatefaq');

Route::get('/admin/contact_us','OtherController@contact_us');
Route::post('/updatecontact_us/{id}','OtherController@updatecontact_us');

Route::get('/howtobuy','OtherController@howtobuy');
Route::post('/updatehowtobuy/{id}','OtherController@updatehowtobuy');


Route::get('/cash_on_delivery','OtherController@COD');
Route::post('/updatecod/{id}','OtherController@updatecod');


Route::get('customermessage','OtherController@customermessage');
Route::get('/customer-sms-delete/{id}','OtherController@customersmsdelete');


Route::get('setting','OtherController@setting');
Route::post('/updatesetting/{id}','OtherController@updatesetting');


Route::get('/CareerAdd','OtherController@CareerAdd');
Route::post('/updateCareerAdd/{id}','OtherController@updateCareerAdd');

Route::get('/announcementadd','OtherController@announcementadd');
Route::post('/insertannouncement','OtherController@insertannouncement');
Route::get('/newsadd','OtherController@newsadd');
Route::post('/insertnews','OtherController@insertnews');


// =========Registration Controller=============
Route::get('sellerlist','registrationListController@sellerlist');
Route::get('selleractivelist','registrationListController@selleractivelist');
Route::get('sellerinactivelist','registrationListController@sellerinactivelist');
Route::get('sellerdelete/{id}','registrationListController@sellerdelete');
Route::get('inactiveseller/{id}','registrationListController@inactiveseller');
Route::get('activeseller/{id}','registrationListController@activeseller');
Route::get('selleraccess/{phone}/{pass}','registrationListController@selleraccess');
Route::get('guestaccess/{id}','registrationListController@guestaccess');
Route::get('GuestList','registrationListController@GuestList');
Route::get('guestregister','registrationListController@guestregister');
Route::post('guestregisterstore','registrationListController@guestregisterstore');
Route::get('GuestListactive','registrationListController@GuestListactive');
Route::get('GuestListinactive','registrationListController@GuestListinactive');
Route::get('GuestListdelete/{id}','registrationListController@GuestListdelete');
Route::get('inactiveguest/{id}','registrationListController@inactiveguest');
Route::get('activeguest/{id}','registrationListController@activeguest');
// ===================Order System==================
Route::get('/payment-control','orderSystemController@payment_control');
Route::post('/updatecontrol','orderSystemController@updatecontrol');
Route::get('/date-to-date-order','orderSystemController@datetodateorder');
Route::post('/date-to-date-order-list','orderSystemController@datetodateorderlist');
Route::get('/search-order','orderSystemController@search_order');
// ==========Amarpay===============
Route::get('/amarpay','orderSystemController@amarpayorderreport');
Route::post('/amarpay-report-list','orderSystemController@amarpayreportlist');

Route::get('/foster-pay-order','orderSystemController@fosterpayorder');
Route::get('/allorderstatus','orderSystemController@allorderstatus');
Route::get('/totalOrder','orderSystemController@totalOrder');
Route::get('/pendingOrder','orderSystemController@pendingOrder');
Route::get('/ProcessOrder','orderSystemController@ProcessOrder');
Route::get('/Shipping-Order','orderSystemController@shippingorder');
Route::get('/onthewayOrder','orderSystemController@onthewayOrder');
Route::get('/CompleteOrder','orderSystemController@CompleteOrder');
Route::get('/RejectOrder','orderSystemController@RejectOrder');
Route::get('/Refound-Order','orderSystemController@RefoundOrder');

Route::get('/exchange-request','orderSystemController@exchange_request');
Route::get('/exchange_request_details/{id}','orderSystemController@exchange_request_details');
Route::post('/update-exchange-request/{id}','orderSystemController@update_exchange_request');
Route::get('/delete_exchange_request/{id}','orderSystemController@delete_exchange_request');

Route::get('/shipping_address/{id}','orderSystemController@shipping_address');
Route::post('/change_shipping','orderSystemController@change_shipping');
Route::get('/processorder_note/{id}','orderSystemController@processorder_note');
Route::get('/rejectorder_note/{id}','orderSystemController@rejectorder_note');
Route::post('/penToProOrder','orderSystemController@penToProOrder');
Route::post('/proToontheOrder','orderSystemController@proToontheOrder');
Route::post('/protoShipping','orderSystemController@protoShipping');
Route::post('/ontheTosuccOrder','orderSystemController@ontheTosuccOrder');
Route::post('/penTorejectOrder','orderSystemController@penTorejectOrder');
Route::post('/rejecttorefundOrder','orderSystemController@rejecttorefundOrder');
Route::get('/clearshopping','orderSystemController@clearshopping');



Route::get('/date-to-date-order-report','orderSystemController@order_report');
Route::post('/date-to-date-order-reporttab','orderSystemController@order_reporttab');

Route::get('/invoice-balance/{invoice}','orderSystemController@invoice_balance_sheet');
Route::get('/invoice-trans/{invoice}','orderSystemController@invoice_trans_sheet');

Route::get('/all-product-report','ProductController@all_product_report');

// ==========Delivery date===============
Route::get('/add-holyday','DeliveryDateController@index');
Route::post('/add-holyday/add','DeliveryDateController@add');
Route::post('/add-holyday/deleteholyday','DeliveryDateController@deleteholyday');
Route::get('/add-holyday/updateholyday/{id}','DeliveryDateController@updateholyday');
Route::post('/add-holyday/insertholyday','DeliveryDateController@insertholyday');


//============ SEO Setting ================
Route::resource('seosetting', SEOController::class);

//============ Page Setting ================
Route::resource('pagecategory', PageCategoryController::class);
Route::resource('page', PageController::class);


//============ Employee Setting ================
Route::resource('employee', EmployeeController::class);



//============ Paymethod Method ================
Route::resource('paymentmethod', PaymentMethodController::class);



// ==========Logout===============
Route::get('/Adminlogout','AdminController@Adminlogout');


});




Route::get('/clear-cache', function() {
    $exitCode = Artisan::call('cache:clear');
    $exitCode = Artisan::call('config:cache');
    return 'DONE'; //Return anything
});

Route::get('/schedule', function () {
            Artisan::call('product:pricechange');
             $notification=array(
            'messege'   =>'Flash Offer Off',
            'alert-type'=>'error'
        );

        return redirect()->back()->with($notification); 
        });


Route::get('/online-pay-order','orderSystemController@online_pay_order');
Route::get('/adminsearchproduct','ProductController@adminsearchproduct');
// Clear route cache:
 // Route::get('/route-cache', function() {
 //     $exitCode = Artisan::call('route:cache');
 //     return 'Routes cache cleared';
 // });

 // Clear config cache:
 // Route::get('/config-cache', function() {
 //     $exitCode = Artisan::call('config:cache');
 //     return 'Config cache cleared';
 // }); 


 // Clear view cache:
 // Route::get('/view-clear', function() {

app/PaymentMethod.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class PaymentMethod extends Model
{
    //
}

app/Http/Controllers/PaymentMethodController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\PaymentMethod;
use Str;
use Image;

class PaymentMethodController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $methods = PaymentMethod::get();
        return view('Admin.paymentmethod.index', compact('methods'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('Admin.paymentmethod.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'name' => 'required| unique:payment_methods',
            'account_holder_name' => 'required',
            'account_number' => 'required',
            'account_type' => 'required',
            'image' => 'required',
            'status' => 'required',
        ]);
        $data = new PaymentMethod();
        $data->name = $request->name;
        $data->account_holder_name = $request->account_holder_name;
        $data->account_number = $request->account_number;
        $data->account_type = $request->account_type;
        $data->status = $request->status;
        $image = $request->file('image');
        if($image)
        {
            $image_name= str::random(10);
            $orginalExtension = $image->getClientOriginalExtension();
            $image_full_name = $image_name.'.'.$orginalExtension;
            $upload_path = public_path('/PaymentMethodImage/');
            $image_url = $upload_path.$image_full_name;
            $success = $image->move($upload_path, $image_full_name);
            $img = Image::make($image_url)->resize(50, 50)->save();
            if($success)
            {
                $data->image = $image_full_name;
            }
        }
        $data->save();
        $notification = array(
            'messege'   => 'Update Successfull',
            'alert-type' => 'success'
        );
        return redirect()->back()->with($notification);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = PaymentMethod::findOrFail($id);

        return view('Admin.paymentmethod.edit', compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = PaymentMethod::findOrFail($id);
        $data->name = $request->name;
        $data->account_holder_name = $request->account_holder_name;
        $data->account_number = $request->account_number;
        $data->account_type = $request->account_type;
        $data->status = $request->status;
        $image = $request->file('image');
        if($image)
        {
            $image_name= str::random(10);
            $orginalExtension = $image->getClientOriginalExtension();
            $image_full_name = $image_name.'.'.$orginalExtension;
            $upload_path = public_path('/PaymentMethodImage/');
            $image_url = $upload_path.$image_full_name;
            $success = $image->move($upload_path, $image_full_name);
            $img = Image::make($image_url)->resize(50, 50)->save();
            if($success)
            {
                $data->image = $image_full_name;
            }
        }
        $data->save();
        $notification = array(
            'messege'   => 'Update Successfull',
            'alert-type' => 'success'
        );
        return redirect()->back()->with($notification);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = PaymentMethod::findOrFail($id);
        $data->delete();
        $notification = array(
            'messege'   => 'Deleted Successfull',
            'alert-type' => 'error'
        );
        return redirect()->back()->with($notification);
    }
}

resources/views/Admin/paymentmethod/create.blade.php
@include('Admin.header')
<div class="main-content">
  <div class="container">

    <br>
    <br>
    <br>
    <br>
    @if ($errors->any())
    <div class="alert alert-danger">
      <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
      </ul>
    </div>
    @endif
    <div class="row">
      <div class="col-md-12">

        <div class="card card-shadow mb-4">
          <div class="card-header">
            <div class="card-title" style="float: left;">
             Add Payment Method
            </div> 
            <a href="{{route('paymentmethod.index')}}"><button class="btn btn-info" style="float: right;">Payment Method List</button></a>
          </div>
          <div class="card-body">
            <form method="post" action="{{route('paymentmethod.store')}}" enctype="multipart/form-data">
             @csrf
             <div class="row">
              <div class="col-md-12">

                <div class="form-group ">
                    <label class="control-label">Name</label>
                    <div class="controls">
                        <input type="text" class="form-control" name="name" placeholder="Name" required="" value="">
                    </div>
                </div>

                <div class="form-group ">
                    <label class="control-label">Account Holder Name</label>
                    <div class="controls">
                        <input type="text" class="form-control" name="account_holder_name" placeholder="Account Holder Name" required="" value="">
                    </div>
                </div>

                <div class="form-group ">
                    <label class="control-label">Account Number</label>
                    <div class="controls">
                        <input type="number" class="form-control" name="account_number" placeholder="Account Number" required="" value="">
                    </div>
                </div>

                <div class="form-group ">
                    <label class="control-label">Account Type</label>
                    <div class="controls">
                        <select name="account_type" id="" class="form-control">
                            <option value="Personal">Personal</option>
                            <option value="Agent">Agent</option>
                        </select>
                    </div>
                </div>

             

                <div class="form-group ">
                    <label class="control-label">Image</label>
                    <div class="controls">
                        <input type="file" class="form-control" name="image" required="" value="">
                    </div>
                </div>
                
                
                <div class="form-group ">
                    <label class="control-label">Status</label>
                    <div class="controls">
                        <select name="status" class="form-control">
                            <option value="1">Active</option>
                            <option value="0">Inaction</option>
                        </select>
                    </div>
                </div>


              </div>
            </div>
            <br>
            <div align="center">
             <input type="submit" name="submit" class="btn btn-success">
           </div>
         </form>
       </div>
     </div>




   </div>
 </div>
</div>
</div>
@include('Admin.footer')


<!--<script src="{{URL::to('/')}}/public/editor3/ckeditor.js"></script> -->

<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.js"></script>

resources/views/Admin/paymentmethod/edit.blade.php
@include('Admin.header')
<div class="main-content">
  <div class="container">

    <br>
    <br>
    <br>
    <br>
    @if ($errors->any())
    <div class="alert alert-danger">
      <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
      </ul>
    </div>
    @endif
    <div class="row">
      <div class="col-md-12">

        <div class="card card-shadow mb-4">
          <div class="card-header">
            <div class="card-title" style="float: left;">
             Edit Payment Method
            </div> 
            <a href="{{route('paymentmethod.index')}}"><button class="btn btn-info" style="float: right;">Payment Method List</button></a>
          </div>
          <div class="card-body">
            <form method="post" action="{{route('paymentmethod.update', $data->id)}}" enctype="multipart/form-data">
             @csrf
             @method('patch')
             <div class="row">
              <div class="col-md-12">

                <div class="form-group ">
                    <label class="control-label">Name</label>
                    <div class="controls">
                        <input type="text" class="form-control" name="name" placeholder="Name" required="" value="{{$data->name}}">
                    </div>
                </div>

                <div class="form-group ">
                    <label class="control-label">Account Holder Name</label>
                    <div class="controls">
                        <input type="text" class="form-control" name="account_holder_name" placeholder="Account Holder Name" required="" value="{{$data->account_holder_name}}">
                    </div>
                </div>

                <div class="form-group ">
                    <label class="control-label">Account Number</label>
                    <div class="controls">
                        <input type="number" class="form-control" name="account_number" placeholder="Account Number" required="" value="{{$data->account_number}}">
                    </div>
                </div>

                <div class="form-group ">
                    <label class="control-label">Account Type</label>
                    <div class="controls">
                        <select name="account_type" id="" class="form-control">
                            <option value="Personal" @php if ($data['account_type'] == 'Personal') { echo "selected"; } @endphp>Personal</option>
                            <option value="Agent" @php if ($data['account_type'] == 'Agent') { echo "selected"; } @endphp>Agent</option>
                        </select>
                    </div>
                </div>

             

                <div class="form-group ">
                    <label class="control-label">Image</label>
                    <div class="controls">
                        @php
                            $path= base_path().'/public/PaymentMethodImage/'.$data->image;
                        @endphp
                        @if($data->image)
                        <img src="{{asset('/public/PaymentMethodImage')}}/{{$data->image}}" alt="">
                        @endif

                        <input type="file" class="form-control" name="image">
                    </div>
                </div>
                
                
                <div class="form-group ">
                    <label class="control-label">Status</label>
                    <div class="controls">
                        <select name="status" class="form-control">
                            <option value="1" @php if ($data['status'] == 1) { echo "selected"; } @endphp>Active</option>
                            <option value="0" @php if ($data['status'] == 0) { echo "selected"; } @endphp>Inactive</option>
                        </select>
                    </div>
                </div>


              </div>
            </div>
            <br>
            <div align="center">
             <input type="submit" name="submit" class="btn btn-success">
           </div>
         </form>
       </div>
     </div>




   </div>
 </div>
</div>
</div>
@include('Admin.footer')


<!--<script src="{{URL::to('/')}}/public/editor3/ckeditor.js"></script> -->

<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.js"></script>

resources/views/Admin/paymentmethod/index.blade.php
@include('Admin.header')

<br>
<br>
<br>






<div class="main-content" style="overflow: hidden;">

            <!--page title start-->
            <div class="page-title" style="float: left;">
                <h4 class="mb-0">
                    <small>Payment Method</small>
                </h4>
              
            </div>
            
         
            <!--page title end-->


            <div class="container" style="overflow-x: scroll; max-height:726px">

                <!-- state start-->
                <div class="row">
                    <div class=" col-sm-12">
                        <div class="mb-4">
                   
                                    <span id="sms"></span>
                            <div class="card-body">
                                <table id="example" class="display nowrap" style="width:100%;text-align:center;">
                                    <thead>
                                    <tr>
                                       <th>SL</th>
                                        <th>Image</th>
                                        <th>Name</th>
                                        <th>Holder Name</th>
                                        <th>Account Number</th>
                                        <th>Account Type</th>
                                        <th>Status</th>
                                        <th>Action</th>
                                    </tr>
                                    </thead>
                                    <tfoot>
                                    <tr>
                                       <th>SL</th>
                                        <th>Image</th>
                                        <th>Name</th>
                                        <th>Holder Name</th>
                                        <th>Account Number</th>
                                        <th>Account Type</th>
                                        <th>Status</th>
                                        <th>Action</th>
                                    </tr>
                                    </tfoot>
                                    <tbody>
                                        @php
                                        $sl=1;
                                        @endphp
                                        @if(isset($methods))
                                        @foreach($methods as $showdata)
                                      
                                      <tr id="tr-{{$showdata->invoice_id}}">
                                        <td data-toggle="tooltip" title="SL">{{$sl++}}</td>
                                        <td data-toggle="tooltip" title="Order ID"><img src="{{asset('/public/PaymentMethodImage')}}/{{$showdata->image}}" alt=""></td>
                                        <td data-toggle="tooltip" title="Order ID">{{ $showdata->name }}</td>
                                        <td data-toggle="tooltip" title="Order ID">{{ $showdata->account_holder_name }}</td>
                                        <td data-toggle="tooltip" title="Order ID">{{ $showdata->account_number }}</td>
                                        <td data-toggle="tooltip" title="Order ID">{{ $showdata->account_type }}</td>

                                        <td>
                                            @if($showdata->status == '0')
                                            <a class="btn btn-warning btn-sm">Inactive</a>
                                            @elseif($showdata->status == '1')
                                              <a class="btn btn-info btn-sm">Active</a>
                                             @endif
                                        </td>
                                        <td>
                                          <div class="row">
                                             <a href="{{route('paymentmethod.edit', $showdata->id)}}" class="btn btn-outline-warning btn-sm mr-2" target="_blank" style="float: left;">Edit</a>

                                            <form action="{{route('paymentmethod.destroy', $showdata->id)}}" method="post">
                                                @csrf
                                                @method('DELETE')
                                                <button class="btn btn-outline-warning btn-sm" style="float: left;">Delete</button>
                                            </form> 
                                          </div>
                                            

                                        </td>
                                    </tr>
                                         @endforeach
                                         @endif
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>


                <!-- state end-->

            </div>
        </div>

@include('Admin.footer')