routes/web.php
Route::get('productstatusactive/{id}','ProductController@productstatusactive');
Route::get('productstatusinactive/{id}','ProductController@productstatusinactive');
Route::post('productdetails','ProductController@productdetails');
Route::get('productimage','ProductController@product_image');
Route::post('multiimage','ProductController@multiimage');
Route::get('activecoupon/{id}','couponController@activecoupon');
Route::get('inactivecoupon/{id}','couponController@inactivecoupon');


// Stock

Route::get('/productstock', 'ProductController@productstock');
Route::post('addproductstock','ProductController@addproductstock');
Route::get('/viewproductstock', 'ProductController@viewproductstock');
Route::get('/deletestock/{id}','ProductController@deletestock');
Route::get('/editstock/{id}','ProductController@editstock');
Route::post('/updateproductstock/{id}','ProductController@updateproductstock');
Route::get('/stockreport','ProductController@stockreport');
Route::post('/getsize','ProductController@getsize');
Route::post('/getcolor','ProductController@getcolor');

Route::get('/deleteadminproduct/{id}','ProductController@deleteadminproduct');


Route::get('/deleteadminproduct/{id}','ProductController@deleteadminproduct');

Route::post('/update-multi-image','ProductController@update_multi_image')->name('admin/update-multi-image');
Route::get('/delete-multi-image/{id}','ProductController@delete_multi_image')->name('admin/delete-multi-image');



// other controller
Route::get('/admin/about_us','OtherController@about_us');
Route::post('/updateabout/{id}','OtherController@updateabout_us');

Route::get('/admin/term&condition','OtherController@term');
Route::post('/updateterm/{id}','OtherController@updateterm');

Route::get('/admin/privacy&policy','OtherController@privacy');
Route::post('/updateprivacy/{id}','OtherController@updateprivacy');

Route::get('/admin/cookie-policy','OtherController@cookie');
Route::post('/updatecookie/{id}','OtherController@updatecookie');

Route::get('/admin/purchasing-policy','OtherController@purchasing');
Route::post('/updatepurchasing/{id}','OtherController@updatepurchasing');

Route::get('/admin/return-policy','OtherController@return_policy');
Route::post('/updatereturn/{id}','OtherController@updatereturn');

Route::get('/admin/seller-policy','OtherController@seller_policy');
Route::post('/updateseller/{id}','OtherController@updateseller');

Route::get('/admin/merchant-zone','OtherController@merchant_zone');
Route::post('/updatemerchantzone/{id}','OtherController@updatemerchantzone');

Route::get('/admin/seller-zone','OtherController@seller_zone');
Route::post('/updatesellerzone/{id}','OtherController@updatesellerzone');

Route::get('/admin/faq','OtherController@faq');
Route::post('/updatefaq/{id}','OtherController@updatefaq');

Route::get('/admin/contact_us','OtherController@contact_us');
Route::post('/updatecontact_us/{id}','OtherController@updatecontact_us');

Route::get('/howtobuy','OtherController@howtobuy');
Route::post('/updatehowtobuy/{id}','OtherController@updatehowtobuy');


Route::get('/cash_on_delivery','OtherController@COD');
Route::post('/updatecod/{id}','OtherController@updatecod');


Route::get('customermessage','OtherController@customermessage');
Route::get('/customer-sms-delete/{id}','OtherController@customersmsdelete');


Route::get('setting','OtherController@setting');
Route::post('/updatesetting/{id}','OtherController@updatesetting');


Route::get('/CareerAdd','OtherController@CareerAdd');
Route::post('/updateCareerAdd/{id}','OtherController@updateCareerAdd');

Route::get('/announcementadd','OtherController@announcementadd');
Route::post('/insertannouncement','OtherController@insertannouncement');
Route::get('/newsadd','OtherController@newsadd');
Route::post('/insertnews','OtherController@insertnews');


// =========Registration Controller=============
Route::get('sellerlist','registrationListController@sellerlist');
Route::get('selleractivelist','registrationListController@selleractivelist');
Route::get('sellerinactivelist','registrationListController@sellerinactivelist');
Route::get('sellerdelete/{id}','registrationListController@sellerdelete');
Route::get('inactiveseller/{id}','registrationListController@inactiveseller');
Route::get('activeseller/{id}','registrationListController@activeseller');
Route::get('selleraccess/{phone}/{pass}','registrationListController@selleraccess');
Route::get('guestaccess/{id}','registrationListController@guestaccess');
Route::get('GuestList','registrationListController@GuestList');
Route::get('guestregister','registrationListController@guestregister');
Route::post('guestregisterstore','registrationListController@guestregisterstore');
Route::get('GuestListactive','registrationListController@GuestListactive');
Route::get('GuestListinactive','registrationListController@GuestListinactive');
Route::get('GuestListdelete/{id}','registrationListController@GuestListdelete');
Route::get('inactiveguest/{id}','registrationListController@inactiveguest');
Route::get('activeguest/{id}','registrationListController@activeguest');
// ===================Order System==================
Route::get('/payment-control','orderSystemController@payment_control');
Route::post('/updatecontrol','orderSystemController@updatecontrol');
Route::get('/date-to-date-order','orderSystemController@datetodateorder');
Route::post('/date-to-date-order-list','orderSystemController@datetodateorderlist');
Route::get('/search-order','orderSystemController@search_order');
// ==========Amarpay===============
Route::get('/amarpay','orderSystemController@amarpayorderreport');
Route::post('/amarpay-report-list','orderSystemController@amarpayreportlist');

Route::get('/foster-pay-order','orderSystemController@fosterpayorder');
Route::get('/allorderstatus','orderSystemController@allorderstatus');
Route::get('/totalOrder','orderSystemController@totalOrder');
Route::get('/pendingOrder','orderSystemController@pendingOrder');
Route::get('/ProcessOrder','orderSystemController@ProcessOrder');
Route::get('/Shipping-Order','orderSystemController@shippingorder');
Route::get('/onthewayOrder','orderSystemController@onthewayOrder');
Route::get('/CompleteOrder','orderSystemController@CompleteOrder');
Route::get('/RejectOrder','orderSystemController@RejectOrder');
Route::get('/Refound-Order','orderSystemController@RefoundOrder');

Route::get('/exchange-request','orderSystemController@exchange_request');
Route::get('/exchange_request_details/{id}','orderSystemController@exchange_request_details');
Route::post('/update-exchange-request/{id}','orderSystemController@update_exchange_request');
Route::get('/delete_exchange_request/{id}','orderSystemController@delete_exchange_request');

Route::get('/shipping_address/{id}','orderSystemController@shipping_address');
Route::post('/change_shipping','orderSystemController@change_shipping');
Route::get('/processorder_note/{id}','orderSystemController@processorder_note');
Route::get('/rejectorder_note/{id}','orderSystemController@rejectorder_note');
Route::post('/penToProOrder','orderSystemController@penToProOrder');
Route::post('/proToontheOrder','orderSystemController@proToontheOrder');
Route::post('/protoShipping','orderSystemController@protoShipping');
Route::post('/ontheTosuccOrder','orderSystemController@ontheTosuccOrder');
Route::post('/penTorejectOrder','orderSystemController@penTorejectOrder');
Route::post('/rejecttorefundOrder','orderSystemController@rejecttorefundOrder');
Route::get('/clearshopping','orderSystemController@clearshopping');



Route::get('/date-to-date-order-report','orderSystemController@order_report');
Route::post('/date-to-date-order-reporttab','orderSystemController@order_reporttab');

Route::get('/invoice-balance/{invoice}','orderSystemController@invoice_balance_sheet');
Route::get('/invoice-trans/{invoice}','orderSystemController@invoice_trans_sheet');

Route::get('/all-product-report','ProductController@all_product_report');

// ==========Delivery date===============
Route::get('/add-holyday','DeliveryDateController@index');
Route::post('/add-holyday/add','DeliveryDateController@add');
Route::post('/add-holyday/deleteholyday','DeliveryDateController@deleteholyday');
Route::get('/add-holyday/updateholyday/{id}','DeliveryDateController@updateholyday');
Route::post('/add-holyday/insertholyday','DeliveryDateController@insertholyday');


//============ SEO Setting ================
Route::resource('seosetting', SEOController::class);

//============ Page Setting ================
Route::resource('pagecategory', PageCategoryController::class);
Route::resource('page', PageController::class);


//============ Employee Setting ================
Route::resource('employee', EmployeeController::class);



//============ Paymethod Method ================
Route::resource('paymentmethod', PaymentMethodController::class);



// ==========Logout===============
Route::get('/Adminlogout','AdminController@Adminlogout');


});




Route::get('/clear-cache', function() {
    $exitCode = Artisan::call('cache:clear');
    $exitCode = Artisan::call('config:cache');
    return 'DONE'; //Return anything
});

Route::get('/schedule', function () {
            Artisan::call('product:pricechange');
             $notification=array(
            'messege'   =>'Flash Offer Off',
            'alert-type'=>'error'
        );

        return redirect()->back()->with($notification); 
        });


Route::get('/online-pay-order','orderSystemController@online_pay_order');
Route::get('/adminsearchproduct','ProductController@adminsearchproduct');
// Clear route cache:
 // Route::get('/route-cache', function() {
 //     $exitCode = Artisan::call('route:cache');
 //     return 'Routes cache cleared';
 // });

 // Clear config cache:
 // Route::get('/config-cache', function() {
 //     $exitCode = Artisan::call('config:cache');
 //     return 'Config cache cleared';
 // }); 


 // Clear view cache:
 // Route::get('/view-clear', function() {

app/SEO.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class SEO extends Model
{
    //
}

app/Http/Controllers/SEOController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\SEO;
use Image;
use Str;
use DB;
use File;


class SEOController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $seo = SEO::first();
        return view('Admin.seo.index', compact('seo'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // return view('Admin.seo.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = new SEO();
        $data->meta_title = $request->meta_title;
        $data->meta_des = $request->meta_des;
        $data->meta_keywords = $request->meta_keywords;
        $data->robots = $request->robots;
        $data->canonical = $request->canonical;
        $data->google_analytics = $request->google_analytics;

        $meta_image = $request->file('meta_image');
        if($meta_image)
        {
            $image_name= str::random(10);
            $orginalExtension = $meta_image->getClientOriginalExtension();
            $image_full_name = $image_name.'.'.$orginalExtension;
            $upload_path = public_path('/seoImage/');
            $image_url = $upload_path.$image_full_name;
            $success = $meta_image->move($upload_path, $image_full_name);
            $img = Image::make($image_url)->resize(1200, 627)->save();
            if($success)
            {
               $data->meta_image = $image_full_name;
            }
        }
        $data->save();

        $notification = array(
            'messege'   => 'Saved Successfull',
            'alert-type' => 'success'
        );
        return redirect()->back()->with($notification);

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = SEO::findOrFail($id);
        $data->meta_title = $request->meta_title;
        $data->meta_des = $request->meta_des;
        $data->meta_keywords = $request->meta_keywords;
        $data->robots = $request->robots;
        $data->canonical = $request->canonical;
        $data->google_analytics = $request->google_analytics;

        $meta_image = $request->file('meta_image');
        if($meta_image)
        {
            $image_name= str::random(10);
            $orginalExtension = $meta_image->getClientOriginalExtension();
            $image_full_name = $image_name.'.'.$orginalExtension;
            $upload_path = public_path('/seoImage/');
            $image_url = $upload_path.$image_full_name;
            $success = $meta_image->move($upload_path, $image_full_name);
            $img = Image::make($image_url)->resize(1200, 627)->save();
            if($success)
            {
               $data->meta_image = $image_full_name;
            }
        }
        $data->save();

        $notification = array(
            'messege'   => 'Update Successfull',
            'alert-type' => 'success'
        );
        return redirect()->back()->with($notification);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/Admin/seo/create.blade.php
@include('Admin.header')



<div class="main-content">
    <div class="container">

<br>
<br>
<br>
<br>
    @if ($errors->any())
        <div class="alert alert-danger">
          <ul>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
          </ul>
        </div>
        @endif
                <div class="row">
                    <div class="col-md-12">
                        <div class="card card-shadow mb-4">
                            <div class="card-header">
                                <div class="card-title" style="float: left;">
                                   	SEO Setting
                                </div> 
                        
                            </div>
                            <div class="card-body">
                                <form id="" method="post" class=" right-text-label-form feedback-icon-form" action="{{route('seosetting.store')}}" enctype="multipart/form-data">
                                    @csrf
                       

                                
                                    <div class="form-group row">
                                        <label class="col-sm-4 control-label" for="username1">Meta title</label>
                                        <div class="col-sm-6">
                                            <input type="text" class="form-control" name="meta_title" placeholder="Meta title" required="">
                                        </div>
                                    </div>
                                    
                                      <div class="form-group row">
                                        <label class="col-sm-4 control-label" for="username1">Meta Description</label>
                                        <div class="col-sm-6">
                                            <textarea name="meta_des" id="" class="form-control" placeholder="Meta Description"></textarea>
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label class="col-sm-4 control-label" for="username1">Meta Keywords</label>
                                        <div class="col-sm-6">
                                            <input type="text" class="form-control"  name="meta_keywords" placeholder="Meta Keywords" >
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label class="col-sm-4 control-label" for="username1">Meta Robots</label>
                                        <div class="col-sm-6">
                                            <input type="text" class="form-control"  name="robots" placeholder="Meta Robots" >
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label class="col-sm-4 control-label" for="username1">Canonical tag</label>
                                        <div class="col-sm-6">
                                            <input type="text" class="form-control"  name="canonical" placeholder="Canonical tag" >
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label class="col-sm-4 control-label" for="username1">Meta Image</label>
                                        <div class="col-sm-6">
                                          
                                            <input type="file" class="form-control"  name="meta_image">
                                            <span>Size: 1200*627px</span>
                                        </div>
                                    </div>


                                    <div class="form-group row">
                                        <label class="col-sm-4 control-label" for="username1">Google Analytics Code</label>
                                        <div class="col-sm-6">
                                            <textarea name="google_analytics" id="" cols="30" rows="10" class="form-control"></textarea>
                                        </div>
                                    </div>


                                    <div class="form-group row">
                                        <div class="col-sm-8 ml-auto">
                                            <button type="submit" class="btn btn-success" name="signup1" value="Sign up">Update</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>







    </div>
</div>








@include('Admin.footer')
<script type="text/javascript">
      function check_all()
      {
      
      if($('#chkbx_all').is(':checked')){
        $('input.check_elmnt2').prop('disabled', false);
        $('input.check_elmnt').prop('checked', true);
        $('input.check_elmnt2').prop('checked', true);
      }else{
        $('input.check_elmnt2').prop('disabled', true);
        $('input.check_elmnt').prop('checked', false);
        $('input.check_elmnt2').prop('checked', false);
        }
    } 
    

    function chekMain(getID){
       
          if($('#linkID-'+getID).is(':checked')){
              
            $("input#sublinkID-"+getID).attr('disabled', false);
            $("input#sublinkID-"+getID).attr('checked', true);
          
          }else{
            $("input#sublinkID-"+getID).attr('disabled', true);
            $("input#sublinkID-"+getID).attr('checked', false);
          
          }
      
        }


</script>

resources/views/Admin/seo/index.blade.php
@include('Admin.header')



<div class="main-content">
    <div class="container">

<br>
<br>
<br>
<br>
    @if ($errors->any())
        <div class="alert alert-danger">
          <ul>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
          </ul>
        </div>
        @endif
                <div class="row">
                    <div class="col-md-12">
                        <div class="card card-shadow mb-4">
                            <div class="card-header">
                                <div class="card-title" style="float: left;">
                                   	SEO Setting
                                </div> 
                        
                            </div>
                            <div class="card-body">
                                <form id="" method="post" class=" right-text-label-form feedback-icon-form" action="{{route('seosetting.update', $seo->id)}}" enctype="multipart/form-data">
                                     @method('patch')
                                    @csrf
                                
                                    <div class="form-group row">
                                        <label class="col-sm-4 control-label" for="username1">Meta title</label>
                                        <div class="col-sm-6">
                                            <input type="text" class="form-control" name="meta_title" placeholder="Meta title" required="" value="{{$seo->meta_title}}">
                                        </div>
                                    </div>
                                    
                                      <div class="form-group row">
                                        <label class="col-sm-4 control-label" for="username1">Meta Description</label>
                                        <div class="col-sm-6">
                                            <textarea name="meta_des" id="" class="form-control" placeholder="Meta Description">{!! $seo->meta_des !!}</textarea>
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label class="col-sm-4 control-label" for="username1">Meta Keywords</label>
                                        <div class="col-sm-6">
                                            <input type="text" class="form-control"  name="meta_keywords" placeholder="Meta Keywords" value="{{$seo->meta_keywords}}">
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label class="col-sm-4 control-label" for="username1">Meta Robots</label>
                                        <div class="col-sm-6">
                                            <input type="text" class="form-control"  name="robots" placeholder="Meta Robots" value="{{$seo->robots}}">
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label class="col-sm-4 control-label" for="username1">Canonical tag</label>
                                        <div class="col-sm-6">
                                            <input type="text" class="form-control"  name="canonical" placeholder="Canonical tag" value="{{$seo->canonical}}">
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label class="col-sm-4 control-label" for="username1">Meta Image</label>
                                        <div class="col-sm-6">
                                          
                                            @php
                                             $path= base_path().'/public/seoImage/'.$seo->meta_image;
                                            @endphp
                                            @if($seo->meta_image)
                                            <img src="{{asset('/public/seoImage')}}/{{$seo->meta_image}}" alt="" class="w-50">
                                            @endif

                                            <input type="file" class="form-control"  name="meta_image">
                                            <span>Size: 1200*627px</span>
                                        </div>
                                    </div>


                                    <div class="form-group row">
                                        <label class="col-sm-4 control-label" for="username1">Google Analytics Code</label>
                                        <div class="col-sm-6">
                                            <textarea name="google_analytics" id="" cols="30" rows="10" class="form-control">{!! $seo->google_analytics !!}</textarea>
                                        </div>
                                    </div>


                                    <div class="form-group row">
                                        <div class="col-sm-8 ml-auto">
                                            <button type="submit" class="btn btn-success" name="signup1" value="Sign up">Update</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>







    </div>
</div>








@include('Admin.footer')
<script type="text/javascript">
      function check_all()
      {
      
      if($('#chkbx_all').is(':checked')){
        $('input.check_elmnt2').prop('disabled', false);
        $('input.check_elmnt').prop('checked', true);
        $('input.check_elmnt2').prop('checked', true);
      }else{
        $('input.check_elmnt2').prop('disabled', true);
        $('input.check_elmnt').prop('checked', false);
        $('input.check_elmnt2').prop('checked', false);
        }
    } 
    

    function chekMain(getID){
       
          if($('#linkID-'+getID).is(':checked')){
              
            $("input#sublinkID-"+getID).attr('disabled', false);
            $("input#sublinkID-"+getID).attr('checked', true);
          
          }else{
            $("input#sublinkID-"+getID).attr('disabled', true);
            $("input#sublinkID-"+getID).attr('checked', false);
          
          }
      
        }


</script>